create table source.cus_dtls_dim (
cus_dtls_sr_key int,
cus_sr_key int,
buss_cus_typ_sr_key int,
cus_sgmnt_sr_key int,
cus_sts_sr_key int,
cus_bs_grp_sr_key int,
cus_insdr_sr_key int,
cus_mrtl_sts_sr_key int,
cus_grp_rgstrd_cptl_sr_key int,
sbv_ref_sr_key int,
sbv_eco_sectr_sr_key int,
sbv_cus_sectr_sr_key int,
sbv_purp_sr_key int,
cus_cls_sr_key int,
brnch_sr_key int,
buss_line_sr_key int,
cus_cif_nbr string,
brnch_cd string,
cus_insdr_cd string,
cus_sts_cd string,
cus_sgmnt_cd string,
cus_cls_cd string,
sbv_ref_cd string,
sbv_eco_sectr_cd string,
sbv_cus_sectr_cd string,
cus_rgstrd_cptl_grp_cd string,
cus_bs_grp_cd string,
buss_line_cd string,
cus_opr_ctry_cd string,
cus_authrsd_cptl float,
cif_clsf string,
cif_buss_typ string,
sbv_comdte_cd string,
sbv_purp_cd string,
sgmnt_net_rev float,
tot_net_incm float,
cus_incn_dt timestamp,
cus_gen string,
cus_mrtl_sts_cd string,
cus_ctz string,
cus_dob timestamp,
resdn_flag string,
cus_gre string,
prev_cus_gre string,
tot_fin_mrk_scrd float,
tot_non_fin_mrk_scrd float,
eff_strt_dt timestamp,
eff_end_dt timestamp,
cob_dt timestamp,
src_sys_cd string,
updtd_by string,
updtd_dtm timestamp,
cus_blck_list_flag int,
cus_sgmnt_typ_cd string,
sts_chng_dt timestamp,
cus_plc_of_brth string,
cus_ref_cntct_sr_key int,
cus_crdt_rtng int,
offcr_cd string,
ib_flag int,
lon_grp int,
exmptn_amt float,
sign_up_sms_auto_red_flag int,
cus_estb_dt timestamp,
cus_svc_flag_sr_key int,
prev_lon_grp int,
cus_lmt_amt_in_lc float,
cus_lmt_expry_dt timestamp,
lon_grp_cic int,
cus_id_typ_cd1 string,
cus_id_nbr1 string,
cus_id_typ_cd2 string,
cus_id_nbr2 string,
cus_id_typ_cd3 string,
cus_id_nbr3 string,
cus_id_typ_cd4 string,
cus_id_nbr4 string )
using iceberg 
tblproperties (
'engine.hive.enabled'='true',
'read.parquet.vectorization.enabled'='true',
'read.parquet.vectorization.batch-size'='10000',
'write.target-file-size-bytes'='536870912',
'write.distribution-mode'='hash',
'write.merge.mode'='merge-on-read',
'write.update.mode'='merge-on-read',
'write.delete.mode'='merge-on-read'
)