
create view integration.fct_customer_account as 
with cte_steam as 
( select dv_hkey_lnk_customer_account, dv_src_ldt
    ,coalesce(lead(dv_src_ldt) over (partition by dv_hkey_lnk_customer_account order by dv_src_ldt), cast('9999-12-31' as date)) as dv_src_ldt_end
    from 
    (
        select dv_hkey_lnk_customer_account, dv_src_ldt
        from integration.pit_customer_account_dly dly 
        union 
        select dv_hkey_lnk_customer_account, dv_src_ldt
        from integration.pit_customer_account_mtd mtd
        union 
        select dv_hkey_lnk_customer_account, dv_src_ldt
        from integration.pit_customer_account_qtd qtd
        union 
        select dv_hkey_lnk_customer_account, dv_src_ldt
        from integration.pit_customer_account_ytd ytd     
    )
)
select 
cte_steam.dv_hkey_lnk_customer_account,
cte_steam.dv_src_ldt,
cte_steam.dv_src_ldt_end,
dly_actv_depst_act_flag,
dly_ldgr_bal_amt_in_lc,
dly_ldgr_bal_amt_in_tc,
dly_intrst_accr_amt_in_lc,
dly_intrst_pd_amt_in_lc,
dly_intrst_pd_amt_in_tc,
dly_debt_brnch_trns_amt_in_lc,
dly_debt_brnch_trns_amt_in_tc,
dly_debt_oth_trns_amt_in_lc,
dly_debt_oth_trns_amt_in_tc,
dly_crdt_brnch_trns_amt_in_lc,
dly_crdt_brnch_trns_amt_in_tc,
dly_crdt_oth_trns_amt_in_lc,
dly_crdt_oth_trns_amt_in_tc,
dly_nbr_debt_brnch_trns,
dly_nbr_debt_oth_trns,
dly_nbr_crdt_brnch_trns,
dly_nbr_crdt_oth_trns,
dly_nii_amt_in_lc,
dly_nii_amt_in_tc,
dly_fund_cst_amt_in_lc,
dly_fund_cst_amt_in_tc,
dly_fee_incm_amt_in_lc,
dly_fee_incm_amt_in_tc,
dly_net_intrst_mrgn_pct,
dly_depst_statry_rsrv_in_lc,
dly_depst_statry_rsrv_in_tc,
dly_insrnce_prmum_amt_in_lc,
dly_insrnce_prmum_amt_in_tc,
dly_avg_intrst_amt_in_lc,
dly_avg_intrst_amt_in_tc,
dly_od_intrst_accr_amt_in_lc,
dly_od_intrst_accr_amt_in_tc,
dly_ftp_amt_in_lc,
dly_ftp_amt_in_tc,
dly_acum_sav_lte_depst_amt_in_lc,
dly_acum_sav_lte_depst_amt_in_tc,
dly_ldgrbal_act_opng_tdy_in_lc,
dly_ldgrbal_act_opng_tdy_in_tc,
dly_ldgr_bal_1m_6mth_in_lc,
dly_ldgr_bal_1m_6mth_in_tc,
dly_trmday_ostd_bal_amt_in_lc,
dly_trmday_new_ostd_bal_amt_in_lc,
dly_pnlty_intrst_amt_in_lc,
dly_pnlty_intrst_amt_in_tc,
mtd_actv_depst_act_flag,
    mtd_ldgr_bal_amt_in_lc,
    mtd_ldgr_bal_amt_in_tc,
    mtd_avg_ldgr_bal_amt_in_lc,
    mtd_avg_ldgr_bal_amt_in_tc,
    mtd_intrst_accr_amt_in_lc,
    mtd_intrst_pd_amt_in_lc,
    mtd_intrst_pd_amt_in_tc,
    mtd_debt_brnch_trns_amt_in_lc,
    mtd_debt_brnch_trns_amt_in_tc,
    mtd_debt_oth_trns_amt_in_lc,
    mtd_debt_oth_trns_amt_in_tc,
    mtd_crdt_brnch_trns_amt_in_lc,
    mtd_crdt_brnch_trns_amt_in_tc,
    mtd_crdt_oth_trns_amt_in_lc,
    mtd_crdt_oth_trns_amt_in_tc,
    mtd_nbr_debt_brnch_trns,
    mtd_nbr_debt_oth_trns,
    mtd_nbr_crdt_brnch_trns,
    mtd_nbr_crdt_oth_trns,
    mtd_nii_amt_in_lc,
    mtd_nii_amt_in_tc,
    mtd_fund_cst_amt_in_lc,
    mtd_fund_cst_amt_in_tc,
    mtd_fee_incm_amt_in_lc,
    mtd_fee_incm_amt_in_tc,
    mtd_depst_statry_rsrv_in_lc,
    mtd_depst_statry_rsrv_in_tc,
    mtd_insrnce_prmum_amt_in_lc,
    mtd_insrnce_prmum_amt_in_tc,
    mtd_avg_intrst_amt_in_lc,
    mtd_avg_intrst_amt_in_tc,
    mtd_od_intrst_accr_amt_in_lc,
    mtd_od_intrst_accr_amt_in_tc,
    mtd_avg_intrst_rte,
    mtd_ftp_amt_in_lc,
    mtd_ftp_amt_in_tc,
    mtd_acum_sav_incr_amt_depst_cnt,
    mtd_acum_sav_lte_depst_amt_in_lc,
    mtd_acum_sav_lte_depst_amt_in_tc,
    mtd_acum_sav_depst_amt_in_lc,
    mtd_acum_sav_depst_amt_in_tc,
    mtd_ldgrbal_act_opng_tdy_in_lc,
    mtd_ldgrbal_act_opng_tdy_in_tc,
    mtd_ldgr_bal_1m_6mth_in_lc,
    mtd_ldgr_bal_1m_6mth_in_tc,
    mtd_trmday_ostd_bal_amt_in_lc,
    mtd_trmday_new_ostd_bal_amt_in_lc,
    mtd_ldgr_bal_td_act_pmture_tdy_lc,
    mtd_ldgr_bal_td_act_pmture_tdy_tc,
    mtd_pnlty_intrst_amt_in_lc,
    mtd_pnlty_intrst_amt_in_tc,
        qtd_actv_depst_act_flag,
        qtd_ldgr_bal_amt_in_lc,
        qtd_ldgr_bal_amt_in_tc,
        qtd_avg_intrst_amt_in_tc,
        qtd_avg_ldgr_bal_amt_in_lc,
        qtd_avg_ldgr_bal_amt_in_tc,
        qtd_intrst_accr_amt_in_lc,
        qtd_intrst_pd_amt_in_lc,
        qtd_intrst_pd_amt_in_tc,
        qtd_debt_brnch_trns_amt_in_lc,
        qtd_debt_brnch_trns_amt_in_tc,
        qtd_debt_oth_trns_amt_in_lc,
        qtd_debt_oth_trns_amt_in_tc,
        qtd_crdt_brnch_trns_amt_in_lc,
        qtd_crdt_brnch_trns_amt_in_tc,
        qtd_crdt_oth_trns_amt_in_lc,
        qtd_crdt_oth_trns_amt_in_tc,
        qtd_nbr_debt_brnch_trns,
        qtd_nbr_debt_oth_trns,
        qtd_nbr_crdt_brnch_trns,
        qtd_nbr_crdt_oth_trns,
        qtd_nii_amt_in_lc,
        qtd_nii_amt_in_tc,
        qtd_fund_cst_amt_in_lc,
        qtd_fund_cst_amt_in_tc,
        qtd_fee_incm_amt_in_lc,
        qtd_fee_incm_amt_in_tc,
        qtd_depst_statry_rsrv_in_lc,
        qtd_depst_statry_rsrv_in_tc,
        qtd_insrnce_prmum_amt_in_lc,
        qtd_insrnce_prmum_amt_in_tc,
        qtd_od_intrst_accr_amt_in_lc,
        qtd_od_intrst_accr_amt_in_tc,
        qtd_avg_intrst_rte,
        qtd_ftp_amt_in_lc,
        qtd_ftp_amt_in_tc,
        qtd_ldgrbal_act_opng_tdy_in_lc,
        qtd_ldgrbal_act_opng_tdy_in_tc,
        qtd_trmday_ostd_bal_amt_in_lc,
        qtd_trmday_new_ostd_bal_amt_in_lc,
        qtd_pnlty_intrst_amt_in_lc,
        qtd_pnlty_intrst_amt_in_tc,
        ytd_actv_depst_act_flag,
            ytd_ldgr_bal_amt_in_lc,
            ytd_ldgr_bal_amt_in_tc,
            ytd_avg_ldgr_bal_amt_in_lc,
            ytd_avg_ldgr_bal_amt_in_tc,
            ytd_intrst_accr_amt_in_lc,
            ytd_intrst_pd_amt_in_lc,
            ytd_intrst_pd_amt_in_tc,
            ytd_debt_brnch_trns_amt_in_lc,
            ytd_debt_brnch_trns_amt_in_tc,
            ytd_debt_oth_trns_amt_in_lc,
            ytd_debt_oth_trns_amt_in_tc,
            ytd_crdt_brnch_trns_amt_in_lc,
            ytd_crdt_brnch_trns_amt_in_tc,
            ytd_crdt_oth_trns_amt_in_lc,
            ytd_crdt_oth_trns_amt_in_tc,
            ytd_nbr_debt_brnch_trns,
            ytd_nbr_debt_oth_trns,
            ytd_nbr_crdt_brnch_trns,
            ytd_nbr_crdt_oth_trns,
            ytd_nii_amt_in_lc,
            ytd_nii_amt_in_tc,
            ytd_fund_cst_amt_in_lc,
            ytd_fund_cst_amt_in_tc,
            ytd_fee_incm_amt_in_lc,
            ytd_fee_incm_amt_in_tc,
            ytd_depst_statry_rsrv_in_lc,
            ytd_depst_statry_rsrv_in_tc,
            ytd_insrnce_prmum_amt_in_lc,
            ytd_insrnce_prmum_amt_in_tc,
            ytd_avg_intrst_amt_in_lc,
            ytd_avg_intrst_amt_in_tc,
            ytd_avg_intrst_rte,
            ytd_od_intrst_accr_amt_in_lc,
            ytd_od_intrst_accr_amt_in_tc,
            ytd_ftp_amt_in_lc,
            ytd_ftp_amt_in_tc,
            ytd_ldgrbal_act_opng_tdy_in_lc,
            ytd_ldgrbal_act_opng_tdy_in_tc,
            ytd_trmday_ostd_bal_amt_in_lc,
            ytd_trmday_new_ostd_bal_amt_in_lc,
            ytd_pnlty_intrst_amt_in_lc,
            ytd_pnlty_intrst_amt_in_tc,
from cte_steam 
join integration.pit_customer_account_dly cte_dly
on cte_dly.dv_hkey_lnk_customer_account = cte_steam.dv_hkey_lnk_customer_account
and cte_dly.dv_src_ldt <= cte_steam.dv_src_ldt
and cte_dly.dv_src_ldt_end >= cte_steam.dv_src_ldt_end
join integration.pit_customer_account_mtd cte_mtd 
on cte_mtd.dv_hkey_lnk_customer_account = cte_steam.dv_hkey_lnk_customer_account
and cte_mtd.dv_src_ldt <= cte_steam.dv_src_ldt
and cte_mtd.dv_src_ldt_end >= cte_steam.dv_src_ldt_end
join integration.pit_customer_account_qtd cte_qtd
on cte_qtd.dv_hkey_lnk_customer_account = cte_steam.dv_hkey_lnk_customer_account
and cte_qtd.dv_src_ldt <= cte_steam.dv_src_ldt
and cte_qtd.dv_src_ldt_end >= cte_steam.dv_src_ldt_end
join integration.pit_customer_account_ytd cte_ytd
on cte_ytd.dv_hkey_lnk_customer_account = cte_steam.dv_hkey_lnk_customer_account
and cte_ytd.dv_src_ldt <= cte_steam.dv_src_ldt
and cte_ytd.dv_src_ldt_end >= cte_steam.dv_src_ldt_end